#!/bin/bash

set -e

source /usr/libexec/s2i/env

if [ "$DEV_MODE" == true ] ; then
	set -x
fi

echo "---> Installing application source"
cp -Rfp /tmp/src/. ./

echo  "---> Creating Instance directory"
mkdir -p /opt/app-root/src/instance/data

echo "---> Fix permissions on app-root"
fix-permissions /opt/app-root